### ISSUE TITLE
Remove <b> tag around_email when forget password message is shown

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/nilavu#1003]
i try to reset my password. it shows as
We found an account that matches <bold> rajeshr@megam.io </bold>, you should receive an email with instructions on how to reset your password shortly.

**Comment by indykish** [comment]
@rajesh-rajagopal  Enlighten me on the change needed.

**Comment by indykish** [comment]
fix is to make the bold tags around rajeshr@megam.io go away.
