### ISSUE TITLE
Launcher does not expand or respond to selecting VM/App

### ISSUE THREAD

**Issue by jaeko44** [megamsys/nilavu#1010]
![ss 2016-07-28 at 09 50 48](https://cloud.githubusercontent.com/assets/9289791/17211545/696bfe46-550d-11e6-8874-725dbc6ee633.png)

Clicking on VM/App does nothing.

Steps to recreate bug: 
1. Click Create VM/App
2. Select VM/App (it will expand here as expected)
3. Continue to end & launch or press X in between 
4. Click Create VM/App 
5. Your last choice (VM/App) will be highlighted and you will not be able to expand it.

Expected Action: 
Return to where the customer previously was if he clicked 'x' or return to original default if user clicked 'launch' and the VM/App was launched (no error).

**Comment by indykish** [comment]
@jaeko44  You'll have to refresh the page by having the url in location bar as `http://cloud.det.io`

This is a dup #963

Ya. Annoying bug.

The UI looks polished.
