### ISSUE TITLE
Aesthetic: VM management page, the  icons  can be made better

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#1015]
1. Tabs name visible so mild 
2. Icons buttons not aligned well

![vm-management page](https://cloud.githubusercontent.com/assets/13815978/17239072/e749685a-557e-11e6-9ed6-9a6ad6c7c320.png)

**Comment by indykish** [comment]
@jaeko44  You can check the VM Management page as well for the aesthetics.

**Comment by indykish** [comment]
@jaeko44  Liked these colors are good here. 

![management_icons](https://cloud.githubusercontent.com/assets/1402479/18383035/3fea27d6-76a1-11e6-93cd-ea95709f4cfa.png)

**Comment by indykish** [comment]
Fixed in https://gitlab.com/megamsys/nilavu.git (MegamVertice/VirtEngine - Complete Edition)
