### ISSUE TITLE
Tosca type structure is to be changed 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#1019]
like vertice.app.java , vertice.service.redis ...
bitnami.app.wordpress ...
docker.github.jenkins ...

**Comment by indykish** [comment]
Basically the first word `tosca` will have meaningfull setting `vertice` or `bitnami` or ... anybody else.

-- provider (`eg: vertice, bitnami..`)
----- category  (`eg: collaboration, app, service`)
------- subcategory/name (`eg: jenkins, wordpress`)

**Comment by indykish** [comment]
https://docs.google.com/a/megam.io/document/d/1SUxrU5hAribOHfbmZ2EEj4ur2PLbxMzP5yXuzpjHeGM/edit?usp=sharing
