### ISSUE TITLE
When refreshing any page in nilavu it raise the routing error

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/nilavu#1021]
[](
![screenshot from 2016-08-03 18-34-58](https://cloud.githubusercontent.com/assets/17096693/17366531/56a35db8-59a9-11e6-8726-ad3ac060fb14.png)

**Comment by indykish** [comment]
Steps:
1. Login
2. Click `My Profile`
3. Hit `enter` by the clicking the `with url in the location`

Basically as its the DOM we do a `json` request, but when we do `step 3.` we do `html` requests.

**Comment by indykish** [comment]
Fixed in https://gitlab.com/megamsys/nilavu.git (MegamVertice/VirtEngine - Complete Edition)
