### ISSUE TITLE
Topic.js Model - No data regarding the state of the VM (wether shut or online)

### ISSUE THREAD

**Issue by jaeko44** [megamsys/nilavu#1029]
The only object I found regarding the state was whether it is launched or not:

status = { message: launched, predeploying: true }

Can you instead return status = { state: offline/online/restarting , message, predeploying } from the back-end as I need that data.

**Comment by jaeko44** [comment]
Also, even though predeploy_finished is set to true the predeploy page is still being displayed every time I create a new session (login again).

**Comment by rajthilakmca** [comment]
@jaeko44 predeploy page working with mock events data, so the vm status doesn't appear correctly. we will connect original events data to predeploy page by next build of nilavu.

**Comment by indykish** [comment]
@jaeko44  Here is the events for a successful run (few typo's in the message have be corrected). https://megamioteam.slack.com/files/rajeshr/F1V54ME7K/events_for_torpedo.txt.

`If you start, you will see`STARTING, STARTED`or and`ERROR` and a list of chronological events that happened before it.
