### ISSUE TITLE
Aesthetic: signin page (logo - DET.io or Vertice) shall be centered.

### ISSUE THREAD

**Issue by indykish** [megamsys/nilavu#1030]
![det_signin](https://cloud.githubusercontent.com/assets/1402479/17504880/7177bc72-5e1a-11e6-81dc-54a5672334df.png)

**Comment by jaeko44** [comment]
Fixed on next pull request.

**Comment by vinomca-megam** [comment]
are you fix this issue that you sent on the pull request @jaeko44

**Comment by vinomca-megam** [comment]
after merge your pull request the login logo not in center

![screenshot from 2016-08-24 11-06-01](https://cloud.githubusercontent.com/assets/17096693/17920180/7d625754-69f0-11e6-9c94-1d4723899d18.png)

**Comment by jaeko44** [comment]
It looks centered to me?

**Comment by jaeko44** [comment]
![center-logo](https://cloud.githubusercontent.com/assets/9289791/17928249/2b1afc4c-6a3d-11e6-94d9-477d44ab3533.png)

**Comment by vinomca-megam** [comment]
Ok
