### ISSUE TITLE
Aesthetic: vm management page was collapsed

### ISSUE THREAD

**Issue by rajthilakmca** [megamsys/nilavu#1039]
i merged presignup page and presignup.css, then the vm management page was collapsed

![after_add_presignup_css](https://cloud.githubusercontent.com/assets/3692486/17515038/b44dd610-5e53-11e6-97c7-6b49c281ad6a.png)

**Comment by indykish** [comment]
@jaeko44  We @rajthilakmca found that the `.scss` of `tabs` in presignup was interfering with `management page`

We use too many tabs.. :)

**Comment by jaeko44** [comment]
Yeah, will fix this when nilavu is running again tomorrow.

**Comment by jaeko44** [comment]
Fixed on next pull request.

**Comment by vinomca-megam** [comment]
Profile Management page also collasped

![screenshot from 2016-09-01 11-20-11](https://cloud.githubusercontent.com/assets/17096693/18156989/1d0184ae-7038-11e6-81ee-a3b0577daa54.png)
