### ISSUE TITLE
Aesthetic: forgot password alignment  

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/nilavu#1046]
![screenshot from 2016-08-11 13-21-54](https://cloud.githubusercontent.com/assets/17096693/17581978/bf7a616a-5fc6-11e6-84fc-12a0a53b4ee4.png)

**Comment by indykish** [comment]
@jaeko44  This is related to #1039, where the scss behaviour for `tabs` is changed but used by others.

**Comment by jaeko44** [comment]
Fixed on next pull request.
