### ISSUE TITLE
UI - Closing the Create VM Modal causes the page to refresh

### ISSUE THREAD

**Issue by jaeko44** [megamsys/nilavu#1063]

**Comment by vinomca-megam** [comment]
Closing the create VM Modal without the page refresh can't extends to create another VM. Actually Modal only to be refresh.We will fix it soon.Page refresh is the temporary fix only.

**Comment by indykish** [comment]
@vinomca-megam  At-least as a stopgap measure, we could redirect to root (/). I am thinking this shall be better than showing a blank page.

**Comment by indykish** [comment]
I find this annoying while testing.

**Comment by indykish** [comment]
The original bug 
`When closing the modal and opening it again, selecting Application/VM does nothing`

This is happening with 
`VNC modal` as well.

**Comment by indykish** [comment]
After 1.5RC we make a change of the new-launcher like here.

We'll get rid of the new-launcher modal.
![virtengine_vertice_new](https://cloud.githubusercontent.com/assets/1402479/18536888/a9b0b974-7b1e-11e6-8413-45e8219d5c1a.png)

**Comment by indykish** [comment]
Fixed in https://gitlab.com/megamsys/nilavu.git

And the 2.0 has an improved launcher :)
