### ISSUE TITLE
Aesthetic: Pre Signup Step1 missing beautification after the latest css update.

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/nilavu#1066]
![screenshot from 2016-08-24 11-57-43](https://cloud.githubusercontent.com/assets/17096693/17920420/06b0b5a4-69f2-11e6-8cfa-e92cdb4ddef1.png)

**Comment by jaeko44** [comment]
Seems like the CSS Is not being read because there is two ID's 

`<section id="collection presignup" class="collection">
`
Is it safe to remove the collection ID from the subscriptions/show.hbs file? as that will fix the css selectors.

**Comment by vinomca-megam** [comment]
there is no CSS for collection
