### ISSUE TITLE
Clicking Step1 / Step2 / Step3 Should only work backwards

### ISSUE THREAD

**Issue by jaeko44** [megamsys/nilavu#1072]
For example, if a user is within step 3 -> then he should be able to go back to 2/1 however if he is within step 1 he should not be able to click step 3 to view the Summary page in Create VM Modal.

**Comment by indykish** [comment]
This is no longer valid. As we are moving to a refined format due bugs/usability in modal.

Hence closing this issue.

![new_launcher](https://cloud.githubusercontent.com/assets/1402479/18581907/45e87a64-7c20-11e6-8aba-c40b347a8a28.png)
