### ISSUE TITLE
Login failed email or password incorrect 

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/nilavu#1076]
End HTTP Request Data.
App 20627 stdout: [2016-08-26T07:22:04+00:00] DEBUG: {
App 20627 stdout:   "code":401,
App 20627 stdout:   "msg_type":"error",
App 20627 stdout:   "msg":"Authentication failure using the email/apikey combination. \n'Authorization failure for 'email:' HMAC doesn't match: 'ranjithar1992@gmail.com'.'\nverify the email and api key combination.\n            ",
App 20627 stdout:   "more":"null",
App 20627 stdout:   "json_claz":"Megam::Error",
App 20627 stdout:   "links":"Forum   :http://docs.megam.io/discuss\nDocs    :http://docs.megam.io\nSupport :http://support.megam.io"
App 20627 stdout: }
App 20627 stdout: [2016-08-26T07:22:04+00:00] DEBUG: RESPONSE ERR: Ruby Object
App 20627 stdout: [2016-08-26T07:22:04+00:00] DEBUG: json_claz      =Megam::Error
App 20627 stdout: some_msg       ={:code=>401, :msg_type=>"error", :msg=>"Authentication failure using the email/apikey combination. \n'Authorization failure for 'email:' HMAC doesn't match: 'ranjithar1992@gmail.com'.'\nverify the email and api key combination.\n            ", :links=>"Forum   :http://docs.megam.io/discuss\nDocs    :http://docs.megam.io\nSupport :http://support.megam.io"}
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.11ms)
Completed 200 OK in 21ms (Views: 0.7ms)

**Comment by vinomca-megam** [comment]
Started POST "/sessions" for 127.0.0.1 at 2016-08-29 10:49:39 +0530
Processing by SessionsController#create as _/_
  Parameters: {"email"=>"ss11@gmail.com", "password"=>"[FILTERED]"}
FASCADE Megam::Account::show 
START Megam::Account.show

> email: ss11@gmail.com
> password: MTIzNDU2Nzg=
> host: 192.168.0.117
> RUN_NOW Megam::Account.show 
> App 5587 stdout: --> (/accounts/ss11@gmail.com)
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: START
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: > expects: 200
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: > method: get
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: > body: 
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: HTTP Request Data:
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: > HTTP http://192.168.0.117
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: > path: /v2/accounts/ss11@gmail.com
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: > body: 
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: > headers: {"Accept"=>"application/json", "Accept-Encoding"=>"gzip", "User-Agent"=>"megam-api/1.5.7", "X-Ruby-Version"=>"2.3.1", "X-Ruby-Platform"=>"x86_64-linux-gnu", "X-Megam-HMAC"=>"ss11@gmail.com:8100c3bfbc15303ef42f18a19834365a04004e8b", "X-Megam-DATE"=>"2016-08-29 10:49", "X-Megam-ORG"=>"", "X-Megam-PUTTUSAVI"=>"true"}
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: > host: 192.168.0.117
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: > nonblock: false
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: > scheme: http
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: End HTTP Request Data.
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: {
> App 5587 stdout:   "code":401,
> App 5587 stdout:   "msg_type":"error",
> App 5587 stdout:   "msg":"Authentication failure using the email/apikey combination. \n'Authorization failure for 'email:' HMAC doesn't match: 'ss11@gmail.com'.'\nverify the email and api key combination.\n            ",
> App 5587 stdout:   "more":"null",
> App 5587 stdout:   "json_claz":"Megam::Error",
> App 5587 stdout:   "links":"Forum   :http://docs.megam.io/discuss\nDocs    :http://docs.megam.io\nSupport :http://support.megam.io"
> App 5587 stdout: }
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: RESPONSE ERR: Ruby Object
> App 5587 stdout: [2016-08-29T10:49:39+05:30] DEBUG: json_claz      =Megam::Error
> App 5587 stdout: some_msg       ={:code=>401, :msg_type=>"error", :msg=>"Authentication failure using the email/apikey combination. \n'Authorization failure for 'email:' HMAC doesn't match: 'ss11@gmail.com'.'\nverify the email and api key combination.\n            ", :links=>"Forum   :http://docs.megam.io/discuss\nDocs    :http://docs.megam.io\nSupport :http://support.megam.io"}
> [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.14ms)
> Completed 200 OK in 103ms (Views: 1.8ms)

**Comment by indykish** [comment]
There is no org_id. Probably happens when we use stuff from cookie. (We store the email/pw in cookie I think).
