### ISSUE TITLE
Asethetic:when launch the app the page is not aligned and description details aren't shown there

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/nilavu#1082]
![appcustompage](https://cloud.githubusercontent.com/assets/13765880/18002313/a7bd60e2-6ba4-11e6-99e3-f22168ca3b9d.png)

**Comment by indykish** [comment]
1. The page needs to be make better Dup of #969 
2. The Top header is missing.

**Comment by jaeko44** [comment]
This issue is partially fixed - 1. is fixed, 2 is duplicate of #1081.

Closing this issue.
