### ISSUE TITLE
Passenger startup error

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/nilavu#1084]
App 15219 stdout: 
App 15219 stderr: DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
App 15219 stderr: Please register a mime type using `register_mime_type` then
App 15219 stderr: use `register_compressor` or `register_transformer`.
App 15219 stderr: https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
App 15219 stderr:  (called from <top (required)> at /usr/share/megam/verticenilavu/lib/es6_module_transpiler/sprockets.rb:3)
App 15219 stderr: 
App 15219 stdout: => MEGAM_HOME env: /var/lib/megam.
App 15219 stdout: 
App 15219 stdout:                   _..._       ███╗   ██╗██╗██╗      █████╗ ██╗   ██╗██╗   ██╗
App 15219 stdout:                 .::'   `.     ████╗  ██║██║██║     ██╔══██╗██║   ██║██║   ██║
App 15219 stdout:                :::       :    ██╔██╗ ██║██║██║     ███████║██║   ██║██║   ██║
App 15219 stdout:                :::       :    ██║╚██╗██║██║██║     ██╔══██║╚██╗ ██╔╝██║   ██║
App 15219 stdout:`::.     .'    ██║ ╚████║██║███████╗██║  ██║ ╚████╔╝ ╚██████╔╝
App 15219 stdout:                  `':..-'      ╚═╝  ╚═══╝╚═╝╚══════╝╚═╝  ╚═╝  ╚═══╝   ╚═════╝
App 15219 stdout:  
App 15236 stdout:

**Comment by indykish** [comment]
@rathishvbr  When you commit fixes for VNC, please tag with #1084

**Comment by indykish** [comment]
@ranjithamca  Can you create a packaging issue for `bundle exec production` ?
