### ISSUE TITLE
Aesthetic: Loading spinner will be in center

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/nilavu#1086]
![screenshot from 2016-08-29 15-59-09](https://cloud.githubusercontent.com/assets/17096693/18055098/497d8142-6e24-11e6-8017-34428c0f5cb9.png)

**Comment by jaeko44** [comment]
Fixed on next pull req.

**Comment by vinomca-megam** [comment]
are you changed it locally or going to send a pull request for this fix?

**Comment by jaeko44** [comment]
will push with other commits.
