### ISSUE TITLE
Aesthetic: Loading should be center in Create Spinner

### ISSUE THREAD

**Issue by jaeko44** [megamsys/nilavu#1091]
![ss 2016-08-31 at 10 03 56](https://cloud.githubusercontent.com/assets/9289791/18127962/d820e346-6fc6-11e6-8c1e-409138e3efcd.png)

**Comment by vinomca-megam** [comment]
After merge your pull request the VM management page and profile Management UI collapsed 

![screenshot from 2016-09-01 11-20-11](https://cloud.githubusercontent.com/assets/17096693/18156783/6a711710-7036-11e6-8c9a-1ffe1762e047.png)

Already this problem is happened.please verify it.

**Comment by vinomca-megam** [comment]
Spinner is not center 
![screenshot from 2016-09-01 11-26-26](https://cloud.githubusercontent.com/assets/17096693/18157029/7423910a-7038-11e6-8137-7510d0e452df.png)

**Comment by jaeko44** [comment]
Works in Firefox / Microsoft Edge. Will do a chrome fix.

**Comment by jaeko44** [comment]
Not sure why your VM Management Page is collapsed, works fine locally. In Chrome/Firefox/IE Edge

http://puu.sh/qW4Uz/514d8b2734.png

I think you didn't merge correctly - because also the new padding css class is not being registered

**Comment by indykish** [comment]
@vinomca-megam  Is this still a problem ?

**Comment by jaeko44** [comment]
This is fixed.
