### ISSUE TITLE
Navigation Bar doesn't work on Phones/Tablets

### ISSUE THREAD

**Issue by jaeko44** [megamsys/nilavu#1101]
The Navigation is hidden but there is no way to open it.

**Comment by indykish** [comment]
hmm.. we are responsive. ? Any thing to do in the css.

**Comment by jaeko44** [comment]
need a button to show up when the navbar is hidden that expands the navbar.

**Comment by jaeko44** [comment]
Or will it be just better to implement the new navbar? What do you think?

**Comment by indykish** [comment]
Yeah the current navbar is old and needs polishing. 

I liked this #1031 ? Do u still have the code for it ? That will close this issue as well.

**Comment by jaeko44** [comment]
Yes I still do, I will implement the new navbar.

**Comment by indykish** [comment]
Our UI is already sharp. Looking forward to see a cool Navbar.
