### ISSUE TITLE
Aesthetic: Reset password modal needs to be made bigger.

### ISSUE THREAD

**Issue by indykish** [megamsys/nilavu#1113]
I have the latest code (#1107 new nav bar update).

![megam_reset_pw](https://cloud.githubusercontent.com/assets/1402479/18237716/4c3dc8a0-7352-11e6-9355-b3848397d41b.png)

**Comment by jaeko44** [comment]
Good spot, will fix.

**Comment by jaeko44** [comment]
Hey @indykish 

This didn't need to be reverted with the new navbar, it is specific to the reset password modal. Can you re merge this back into the branch.

**Comment by indykish** [comment]
@jaeko44 Sure.
