### ISSUE TITLE
Login via GitHub hangs

### ISSUE THREAD

**Issue by jaeko44** [megamsys/nilavu#1115]
![ss 2016-09-05 at 03 21 23](https://cloud.githubusercontent.com/assets/9289791/18238094/7c89866e-737c-11e6-88c0-8f826a4f1ee5.png)

This might be simply a local issue, since my Nilavu isn't connected to a database. Registering an account through email/password lets me 'login' but I can't login again to that same account because it doesn't exist. So it might be causing the github failure, please double check on your side to make sure it works.

**Comment by indykish** [comment]
@jaeko44  I didn't understand this problem.  Can you explain the steps you did to recreate ?
