### ISSUE TITLE
Retrofit fixes 1107, 1109 and merge their branches after 1.5 RC.

### ISSUE THREAD

**Issue by indykish** [megamsys/nilavu#1123]
I rolled back the fixes i merged for #1107 #1109  as i couldn't get the left nav routes 
- dashboard
- torpedo
- apps
  
  working.

With `1107, 1109 code` I found that.
### The url `localhost:3000/torpedo` gets processed as  **HTML**

```
Started HEAD "/torpedo" for 127.0.0.1 at 2016-09-05 20:36:37 +0530
Processing by CockpitsController#torpedo as HTML
```
### The url `localhost:3000/marketplaces` gets processed as JS.

So i moving to merge the branches `revert-1107-1.5`, `revert-1109-1.5` and `revert-1116-1.5` after RC.

As the nav has moved to the header, we need to check when it gets loaded (i mean if ember.js loads it then it will do a `request` as `js`.

**Comment by indykish** [comment]
@jaeko44  I had to revert the fixes, as we need a stable version to work tomorrow and add fixes.

This fix is `nice-to-have` and can be added upon reaching RC.

**Comment by jaeko44** [comment]
Not an issue :)

Stable is better. I'll work on this to get it working by 1.5 release.

When do you think is reasonable for 1.5 release, 3 weeks? 4 weeks? or need more?

**Comment by jaeko44** [comment]
I updated Milestone 1.5 due date to: 

 Due by October 4, 2016

Let's aim by then to have a full release ready incl OBC project & ready for production.

By 2.0 we can add the extended features, such as Solus migrate, App Scaling, etc.

**Comment by indykish** [comment]
Yeah `Oct 4 for 1.5 vertice + OBC 1.0`, we do it. Max this week for nilavu fixes. Then OBC + other stuff for production readiness.

**Comment by indykish** [comment]
@megamsys/megam-dev  Guys get geared towards that.

**Comment by indykish** [comment]
@jaeko44  We merged this back. @rajthilakmca  Will fix the route.
