### ISSUE TITLE
Dashboard grid line items are not aligned.

### ISSUE THREAD

**Issue by indykish** [megamsys/nilavu#1134]
This is a `nice-to-have`
![megam_dash_list](https://cloud.githubusercontent.com/assets/1402479/18268864/50c58164-7443-11e6-9847-be774b28ec5d.png)

**Comment by jaeko44** [comment]
So you want to remove the padding?

**Comment by jaeko44** [comment]
Will be redesigning that. :)

**Comment by indykish** [comment]
Its a low priority thing..

**Comment by jaeko44** [comment]
Understood

**Comment by jaeko44** [comment]
Fixed alignment, will redesign in future.

**Comment by indykish** [comment]
ok. makes sense.
