### ISSUE TITLE
Asethetic: grid list events statusnotification in green

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/nilavu#1163]
![screenshot from 2016-09-07 19-53-41](https://cloud.githubusercontent.com/assets/17096693/18337751/e31f9e00-75b0-11e6-81d0-888f35e64b3f.png)

**Comment by jaeko44** [comment]
Fixed & also fixed aligning:

![ss 2016-09-09 at 02 28 07](https://cloud.githubusercontent.com/assets/9289791/18357655/2140f5c4-7635-11e6-8d72-cf90d0677ae5.png)
