### ISSUE TITLE
Asethetic:  New Launch modal , select boxes "Virtual Machine" & "Application" are not in same size in firefox

### ISSUE THREAD

**Issue by rathishvbr** [megamsys/nilavu#1165]
![bug](https://cloud.githubusercontent.com/assets/19944631/18339030/941b6f8c-75ba-11e6-8ab9-3bf01f91282f.png)

**Comment by indykish** [comment]
@jaeko44  This bug is in `firefox` browser.

In chrome. the boxes appear the same aligned.
![vm_launch](https://cloud.githubusercontent.com/assets/1402479/18339064/e7a29c02-75ba-11e6-8c3e-3ba095c39ee7.png)

**Comment by jaeko44** [comment]
![issue1165](https://cloud.githubusercontent.com/assets/9289791/18356999/9103e1c6-7632-11e6-8058-c10406c481ea.png)
Fixed on next pull request
