### ISSUE TITLE
Wrong pre-deploy page is loading 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#1166]
![screenshot from 2016-09-08 12-10-52](https://cloud.githubusercontent.com/assets/13815978/18339519/923f9d02-75bd-11e6-86c6-839771e5163d.png)

**Comment by indykish** [comment]
@vinomca-megam  Is this done ?

**Comment by vinomca-megam** [comment]
i will check sir

**Comment by indykish** [comment]
@rajesh-rajagopal  Test it and check.

**Comment by rajesh-rajagopal** [comment]
@indykish  predeploy page displays a particular VM events only..

**Comment by indykish** [comment]
Fixed in https://gitlab.com/megamsys/nilavu.git
