### ISSUE TITLE
Asethetic: delete VM modal not aligned

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/nilavu#1171]
![screenshot from 2016-09-08 16-18-47](https://cloud.githubusercontent.com/assets/17096693/18346829/083d7a84-75e0-11e6-825d-8706862d8adf.png)

**Comment by indykish** [comment]
@vinomca-megam  Can you fix this ? My code has fixes for pw.

From:
Jonathan P

```

/ line 9, /usr/share/megam/verticenilavu/app/assets/stylesheets/desktop/modal.scss /

replace height: auto -> height: 100%;

```

**Comment by indykish** [comment]
@vinomca-megam  Is this done ?  or still a problem ?

**Comment by vinomca-megam** [comment]
@indykish ,@jaeko44 i changed the height of the modal in modal.sccs. but modal height not changed.

**Comment by jaeko44** [comment]
Ok I will fix it.

**Comment by indykish** [comment]
Fixed in https://gitlab.com/megamsys/nilavu.git
