### ISSUE TITLE
Custom App lauch public link dosn't work 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#1181]
It doesn't provide scm (public url ) in repo url
{"run_list":["recipe[megam_run]"],"tosca_type":"java","scm":"","provider":"","version":""}

**Comment by vinomca-megam** [comment]
can't understand this issue.could you explain it with screenshot

**Comment by vinomca-megam** [comment]
could you recreate this bug

**Comment by vijaykanthm28** [comment]
@vinomca-megam  when we launch custom application using public url instead github. it doesn't store url in assembly repo url

**Comment by indykish** [comment]
When i fix #1159, i will fix this as well.

**Comment by rajesh-rajagopal** [comment]
@indykish  still the public url in app launch is doesn't work
