### ISSUE TITLE
Doesn't remove duplicate events 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#1182]
![screenshot from 2016-09-09 01-03-39](https://cloud.githubusercontent.com/assets/13815978/18364069/8d410f1c-762a-11e6-8c7b-449aa92fe586.png)

**Comment by indykish** [comment]
More debugging needs to be done to see where the duplicates emerge. We don't refresh and we are in the DOM.

Is it that the api send dups if so, `adding uniq` in api layer can solve it.

**Comment by indykish** [comment]
This bug is noted in https://gitlab.com/megamsy/nilavu.git and will be released in the 1.5.1  fixpack due next week.

Hence closing this.
