### ISSUE TITLE
Aesthetic: When navigating between pages show loading spinner

### ISSUE THREAD

**Issue by jaeko44** [megamsys/nilavu#1183]

**Comment by jaeko44** [comment]
![ss 2016-09-09 at 06 33 23](https://cloud.githubusercontent.com/assets/9289791/18365786/5ea49c6e-7657-11e6-8ab2-89bb459a2388.png)

**Comment by jaeko44** [comment]
we need {{if isLoading"appLoading" "notLoading"}} injected in application.hbs and isLoading should be a variable that gets if the app is transitioning from a page to another. @indykish

**Comment by indykish** [comment]
Ok. will look into it.

**Comment by indykish** [comment]
Fixed in https://gitlab.com/megamsys/nilavu.git
