### ISSUE TITLE
Does not shows an ipaddress details For c/c++  app

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/nilavu#1185]
Launching a C/CPP sdk app in UI. its does not shows an ipaddress in network tab (or) info tab

**Comment by vinomca-megam** [comment]
@rajesh-rajagopal  Is this issue only for C/CPP or else? and could you recreate this bug

**Comment by rajesh-rajagopal** [comment]
its only for C/CPP app.

**Comment by indykish** [comment]
@rajesh-rajagopal  Can you recreate this bug ?

**Comment by rajesh-rajagopal** [comment]
@indykish IP updated in new build. Now the bug is solved.
