### ISSUE TITLE
when launch the docker machine the step2 page is not aligned and icon is not displayed

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/nilavu#1188]
![dockerma](https://cloud.githubusercontent.com/assets/13765880/18379600/00209a82-7691-11e6-9bdc-123e5d897950.png)

**Comment by indykish** [comment]
@ranjithamca  This is moved to `marketplaces.cql`. Hence make changes accordingly.

**Comment by rajthilakmca** [comment]
fixed
