### ISSUE TITLE
Docker tab image is not get loaded and name is not displaying.

### ISSUE THREAD

**Issue by rathishvbr** [megamsys/nilavu#1196]
![screenshot from 2016-09-09 22-41-23](https://cloud.githubusercontent.com/assets/19944631/18396077/59d5da08-76df-11e6-8171-dfa4d5d72244.png)

**Comment by indykish** [comment]
@rathishvbr There was a fix put in recently in Mkt place. Can you check to see if "NONE FOUND doesn't appear" ?

**Comment by indykish** [comment]
@ranjithamca  Can you verify mktplace  on how we do it for **ubuntu** and make the same change for **Dockermachine** ? 

I still see this (marked orange)
![megam_dockermachine](https://cloud.githubusercontent.com/assets/1402479/18499953/1d313090-7a61-11e6-98f6-8d686de200a4.png)
bug.

**Comment by indykish** [comment]
Fixed in https://gitlab.com/megamsys/nilavu.git
