### ISSUE TITLE
Aesthetic: When launching the container the prepackged app don't have the next button.

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/nilavu#1200]
**steps to recreate this bug**
                    choose the container.In step2 page enter the first 3 character of  prepackaged App to search (ex: word press).

![screenshot from 2016-09-12 14-53-09](https://cloud.githubusercontent.com/assets/17096693/18436188/9e772180-7914-11e6-8483-ea26774118a5.png)

**Comment by jaeko44** [comment]
Seems like an aesthetic issue, and the tab is going out of screen (next button is on the right).

**Comment by rajesh-rajagopal** [comment]
Now the next button is visible in the ui and its go the step3 page.category also shows **container**.

![next](https://cloud.githubusercontent.com/assets/18652643/18514207/4b1a3d10-7aae-11e6-9f48-25774d0eeedd.png)
