### ISSUE TITLE
Virtual Machine Management - Support Scaling

### ISSUE THREAD

**Issue by jaeko44** [megamsys/nilavu#1204]
We need to allow the user to modify resources after launch, for example with:
- Storage
  - Existing Storage
    - Resize storage (i'm pretty sure you can only resize up with opennebula)
  - New Storage
    - If supported by opennebula then also attaching block storage (basically second HDD, which can then later be removed from the VM and attached to a new VM).
- Compute Resources: RAM & CPU
  - We combine the above into one resource, so scaling computing resources should also be possible.

**Comment by indykish** [comment]
@ranjithamca  Can you design from the infra and provide inputs ?

**Comment by ranjithamca** [comment]
@indykish  In existing storage we can't expand size. but CPU & Resources can be expand.
In New Storage we can add new disk.

**Comment by ranjithamca** [comment]
@jaeko44 We assume that **Existing storage** means an already mounted parition on root `/`. This expansion isn't possible. 

But a **New storage** can be added as a disk. 

## Steps
1. We will test in OpenNebula first. Then extend it via a new api for in **opennebula-go**.
2. The `Storage` in the UI will have an option named `Attach Disks` which when click shall ask the user to enter the storage size. We will show the amount charge. 

When clicked will call our new api `/disks` and submit a request to serve this request. Vertice will call the API and attach the disk

**Comment by indykish** [comment]
Ok. so we have fixed 

```
If supported by opennebula then also attaching block storage (basically second HDD, which can then later be removed from the VM and attached to a new VM).

```

Rest of the features are attacked in 2.0 under `ElasticVM requirement`.
