### ISSUE TITLE
VNC button is not enable, when the time is crossed out.

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/nilavu#1210]
We check the events status for VNC host updated taken only last ten mins, app launch time is taken more than ten minutes. but the vnc status hit before the ten minutes. so the VNC button is not enabled in the UI.

**Comment by indykish** [comment]
@rajesh-rajagopal  Very good find. Weldone. Well written bug report as well. Keep it up :)

**Comment by indykish** [comment]
@rajthilakmca How do we fix it ? 

Usually DOM has been good for us. Here is where it had screwed us. :)

Should it be a toggle, `once enabled its enabled` ?

**Comment by ranjithamca** [comment]
when launch the vm ,the vm has in bootup state the vnc has been enabled in
one minute..
In nilavu we take before ten minutes records.but i am not know we check
continously in the vm's status in vnchostupdate or running state ah?

RANJITHA R
Platform Developer, Megam Systems
m: 9865693466 a: Megam systems, Plot no. 53, D.no 2/1075, Second cross, Ist
floor, Radha nagar, Perumbakkam, Chennai, Tamil Nadu 600100, India (map)
s: http://megam.io/ e: ranjithar@megam.io
http://twitter.com/Ranjitha

**Comment by indykish** [comment]
:) I added a wrong tag. That was meant for @rajthilakmca
