### ISSUE TITLE
Disk snapshot doesn't put snap id on Request table

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#1213]
id                     | action     | cat_id | category | cattype | created_at                | name
------------------------+------------+--------+----------+---------+---------------------------+----------
 RIP7740718154554064955 | disksaveas |        | snapshot | torpedo | 2016-09-13 10:53:23 +0000 | snapshot

**Comment by vijaykanthm28** [comment]
gateway have to generate new SNAP ID and put records on snapshots table 
same as DISK ATTACH , create DISK ID and put records on disks table

**Comment by indykish** [comment]
Fixed in https://gitlab.com/megamsys/nilavu.git
