### ISSUE TITLE
Administrator Management: Suspended or Deleted VM's from ON should be displayed properly

### ISSUE THREAD

**Issue by jaeko44** [megamsys/nilavu#1214]
If a VM is:
- Deleted in OpenNebula
  - User clicks VM -> He is greeted with a 'VM Deleted by Admin Page'
- Suspended in OpenNebula
  - User clicks VM -> He is greeted with a 'VM Suspended by Admin Page'

**Comment by indykish** [comment]
@ranjithamca  When  @vijaykanthm28 is back,  can we get a design done ? I believe we need to update status/state via cron or something either push or pull. 

Don't know lets figure it out.

**Comment by jaeko44** [comment]
We can simply put a label with the reason of suspension:

For automatic (bill not paid) - the label will explain the account has 'Insufficient credits' and how to fill up.
For manual (by administrator) - the label will explain the VM was manually suspended by administrator, and how to contact support.

**Comment by indykish** [comment]
@vinomca-megam fyi.

@jaeko44  I think this is fixed in last nites build. - This message gets displayed for all `For manual (by administrator)`

**Comment by jaeko44** [comment]
@indykish Nothing displayed for destroyed: http://puu.sh/rMQcw/c6082d4c9f.png 

Neither for suspended as I last checked (after update)

**Comment by indykish** [comment]
@rajesh-rajagopal  Have you connected the `hook` in `ONE`  ?

**Comment by rajesh-rajagopal** [comment]
Cloud.det.io code is updated level
commit 2ddec768 Merge: 9f5b35fe 350e7b42 Author: Jonathan Philipos jonathan@det.io Date: Mon Oct 17 13:44:04 2016 +0000
Merge branch '1.5' into '1.5'

eslint test for admin, fix for vnc, security page toggle for root password, delete msg fix.

See merge request !1214
but suspend/destroy hook status was not changed

**Comment by indykish** [comment]
Fixed in https://gitlab.com/megamsys/nilavu.git
