### ISSUE TITLE
When clicking 'Create Application' pre-select Application instead of VM

### ISSUE THREAD

**Issue by jaeko44** [megamsys/nilavu#1215]
Currently when user clicks Create Application in dashboard, the following pops up, instead we need to select Application: 

![ss 2016-09-14 at 02 44 48](https://cloud.githubusercontent.com/assets/9289791/18500311/d2ebced6-7a89-11e6-8fe2-ed64f1143ca9.png)

**Comment by indykish** [comment]
Fixed in https://gitlab.com/megamsys/nilavu.git
