### ISSUE TITLE
Close the VNC console its goto the predeploy page and display a error message

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/nilavu#1218]
Steps to recreate the bug

In UI launching a VM, Vnc status is updated and console button is enable. after that i click the Console button "**VNC is visible**", then i try to close the vnc window its directly goto the predeploy page and shows an error.
![close vnc button](https://cloud.githubusercontent.com/assets/18652643/18511098/78b2dd04-7a9f-11e6-8e85-a7bab2f4df88.png)

**Comment by indykish** [comment]
Linked to #1063

**Comment by indykish** [comment]
Fixed in https://gitlab.com/megamsys/nilavu.git
