### ISSUE TITLE
Torpedo page name is shown as "Choose App"

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/nilavu#1219]
Torpedo page also shows an **choose app**. Try to change the name.
![name](https://cloud.githubusercontent.com/assets/18652643/18513921/1af292c8-7aad-11e6-8c2a-8c222c59e9c4.png)

**Comment by indykish** [comment]
This is no longer valid. As we are moving to a refined full page view. 

![new_launcher](https://cloud.githubusercontent.com/assets/1402479/18581944/731eb214-7c20-11e6-8957-577d9b8fb94d.png)
