### ISSUE TITLE
Strip the complete edition code in gitlab and upgrade opensource code 

### ISSUE THREAD

**Issue by indykish** [megamsys/nilavu#1233]
As we are marching towards 1.5.x Fixpacks, it will be nice to bring the opensource code to 1.5 stable level.

The complete edition of stable code is here 

[https://gitlab.com/megamsys/nilavu.git (MegamVertice/VirtEngine - Complete Edition)](https://gitlab.com/megamsys/nilavu.git)

We need to port them into the opensource (Minified) edition code here.

**Comment by jagathks** [comment]
Hi,

Looks amazing, may I know the release date pls.

**Comment by jaeko44** [comment]
Hello,

Development of this project has moved to [github.com/virtengine/VirtEngine-UI](http://github.com/virtengine/VirtEngine-UI)

We are releasing 1.6 code base to GitHub very shortly and comes with a lot of fixes.

Also 2.0 Code-base will be released which will be based on a different fork. Credits to [OpenNode](http://opennodecloud.com)

**Comment by indykish** [comment]
There is no plan to provide opensource builds. This project is *Archived*. 

Another proprietary version `2.0` Rio/OS - https://rio.digital was created.
