### ISSUE TITLE
Cant copy .hooks

### ISSUE THREAD

**Issue by nodesrv** [megamsys/nilavu#1236]
Was using this command `# cp ./hooks ./git/.hooks`
And it returned me `cp: cannot stat './hooks': No such file or directory`

**Comment by indykish** [comment]
`hooks are not needed`. I have removed in the doc.

The opensource version is very much down-level that the current level of enterprise code. 

We'll have to strip the enterprise code in [megamsys/nilavu] (https://gitlab.com/megamsys/nilavu] and post the 
it in [opensource](https://github.com/megamsys/nilavu) this month.

Let me know what you wish to do, as you can contact our partner : jonathan@virtengine.com if you are from the hosting industry.
