### ISSUE TITLE
Repo install error

### ISSUE THREAD

**Issue by ghost** [megamsys/nilavu#1237]
Hi!

I am getting the error below when try to get from the repo.

W: Failed to fetch https://get.virtengine.com/repo/1.5/ubuntu/16.04/stable/dists/xenial/InRelease  Connection timed out after 120001 milliseconds

Thanks.

**Comment by indykish** [comment]
@thiagocpv  Use the repo [https://get.megam.io/repo](https://get.megam.io) by following  [https://docs.megam.io](https://docs.megam.io), its active.

**Comment by indykish** [comment]
@thiagocpv  By the way what are you requirements that you wish to use ? 

Your feedback will help us tune our product.

**Comment by ghost** [comment]
Well @indykish I don't have sure if I am using the correct way. I would like to try in my enviroment the virtEngine open source edition. 
PS: I don't have the open nebula. Could you please guide me on that?

Thank you.

**Comment by indykish** [comment]
Yes you can try https://docs.megam.io

You need OpenNebula as well. 
http://docs.opennebula.org/5.2/deployment/opennebula_installation/frontend_installation.html

**Comment by ghost** [comment]
OK, that was my mistake. I will try soon.
Thank you very much!
