### ISSUE TITLE
current_user issue in nilavu 0.6

### ISSUE THREAD

**Issue by morpheyesh** [megamsys/nilavu#235]
Existing user which is onboarded works fine, only when new user is created, it creates a problem. @rajthilakmca  test it by creating a new user and see? @thomasalrin @indykish 

    2015-01-20T15:21:37+05:30] DEBUG: RESPONSE: Ruby Object
    [2015-01-20T15:21:37+05:30] DEBUG: json_claz      =Megam::Account 
    id             =
    email          =
    api_key        =
    authority      =
    created_at     =
    some_msg       ={:code=>201, :msg_type=>"info", :msg=>"Onboard successful. email    
    'currentusertest@nilavu.com' and api_key 'Eja3B0KXkaeWnwVdShRu1A==' is registered.",           
    :links=>"Forum   :https://groups.google.com/forum/?fromgroups=#!forum/megamlive. \nAPI         
    :https://api.megam.co\nDocs    :http://docs.megam.co\nSupport :http://support.megam.co"}
    [2015-01-20T15:21:37+05:30] DEBUG: END(0.608071628s)
    ==> Controller: users, Action: create, User onboarded successfully
    Completed 500 Internal Server Error in 1075ms

    NameError - undefined local variable or method `current_user' for #<User:0x00000007119b88>:
     app/models/user.rb:26:in `send_welcome_email'
      app/controllers/users_controller.rb:82:in `create'
      actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'

**Comment by indykish** [comment]
@rajthilakmca I think is done, please close this issue.
