### ISSUE TITLE
After an instance is deleted, the queue connection between tap and rabbitmq isn't disconnected. 

### ISSUE THREAD

**Issue by morpheyesh** [megamsys/nilavu#444]
websocket does not get disconnected between nilavu and tap

**Comment by indykish** [comment]
@morpheyesh  Reference your log changes commit and close this issue.

**Comment by indykish** [comment]
@morpheyesh  can we close this ?

**Comment by morpheyesh** [comment]
We wont have tap. we are integrating the log streaming to megamd :)
