### ISSUE TITLE
Make the logs shown in nilavu more reliable

### ISSUE THREAD

**Issue by morpheyesh** [megamsys/nilavu#445]
First time log streams on the UI, then the streaming stops on redirection

**Comment by indykish** [comment]
1. Launch aninstance
2. Click overview
3. Click logs (Now your logs will be shown)
4. Now go to dash
5. Click the overview for the same instance
6. Logs doesn't appear.

Also if there are no logs to show, tell the user the same.

Tied to https://github.com/megamsys/nilavu/issues/445

**Comment by indykish** [comment]
@morpheyesh  Reference your commit and close this issue.

**Comment by indykish** [comment]
@morpheyesh  can we close this ?

**Comment by morpheyesh** [comment]
Yes. This can be closed. Logs are very stable now. socket open/close is
perfect.

**Comment by indykish** [comment]
@morpheyesh  Cool. good work dude.
