### ISSUE TITLE
Show vm name in runtime-metrics page

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/nilavu#452]
VM name should be shown in app-overview, metrix and log page.

**Comment by indykish** [comment]
@morpheyesh  can we close this ?

**Comment by morpheyesh** [comment]
No. It is not present in the design provided.

**Comment by indykish** [comment]
ask enixel.

**Comment by indykish** [comment]
@morpheyesh I believe in our discussion you said its fixed. If so please let me know if this can be closed.

**Comment by morpheyesh** [comment]
@indykish Yes it is fixed now by @balajisek

**Comment by indykish** [comment]
@balajisek  Good work balaji.
