### ISSUE TITLE
signup form validation problem

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/nilavu#512]
My navigations
1. https://console.megam.io/signin --> https://console.megam.io/signup --> Clicked Create Account with Empty form --> We flunked page (No validation here)
2. https://console.megam.io/signin --> https://console.megam.io/signup --> Refresh the page --> Clicked Create Account with Empty form --> Form validation working

**Comment by indykish** [comment]
@megamsys/megam-dev  who ever is testing this, verify if this is still a problem.

**Comment by arunkumarsekar06** [comment]
@thomasalrin Please verify this issue once again, form validation is working for both signup and signin.
