### ISSUE TITLE
Problem while connecting to github on app creation 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#514]
Launched an app using bring your own code, it redirects to github id, on that time my app window closed automatically. this issue occur only at the **first time** i try to do.

**Comment by thomasalrin** [comment]
Me too face this problem in console.megam.io on console system reboot. I got 404 error in new window on clicking byoc_git icon. 
Without changing anything, it is working next time.

**Comment by indykish** [comment]
Its a weird problem as  @arunkumarsekar06   debugged it. Only during first time registration, it calls "/" route. I suspect somebody is calling `:before_action: stick_keys`

**Comment by indykish** [comment]
No point keep this problem open. Closing it.
