### ISSUE TITLE
bundle update pulls s3 gem from https://github.com/thomasalrin/s3

### ISSUE THREAD

**Issue by indykish** [megamsys/nilavu#522]
Did a bundle update with the merged code.
Found this line.

```
Using s3 0.3.23 from https://github.com/thomasalrin/s3 (at master)
```

If we have changes to s3 gem, can we use `https://github.com/megamsys/s3` or better yet send a pullrequest to the maintainer ?

**Comment by thomasalrin** [comment]
Working on it https://github.com/thomasalrin/s3/tree/master/lib/ceph

**Comment by thomasalrin** [comment]
https://github.com/megamsys/s3/pull/1 merge it and give pull request to https://github.com/qoobaa/s3
