### ISSUE TITLE
Marketplace service not bind with apps

### ISSUE THREAD

**Issue by arunkumarsekar06** [megamsys/nilavu#548]
```
   ,--.!,
__/   -*-
```

  ,####.  '|`
  ######
`####'                !We flunked!

(o_o) Jee..I couldn't figure out.

no implicit conversion of nil into String
/home/megam/code/megam/workspace/nilavu/app/models/base_fascade.rb:75:in `rescue in api_request'
/home/megam/code/megam/workspace/nilavu/app/models/base_fascade.rb:62:in`api_request'
/home/megam/code/megam/workspace/nilavu/app/models/assembly.rb:45:in `update'
/home/megam/code/megam/workspace/nilavu/app/controllers/oneapps_controller.rb:39:in`block in bind_service'
/home/megam/code/megam/workspace/nilavu/app/controllers/oneapps_controller.rb:51:in `binded_service?'
/home/megam/code/megam/workspace/nilavu/app/controllers/oneapps_controller.rb:38:in`bind_service'
/home/megam/code/megam/workspace/nilavu/app/controllers/application_controller.rb:123:in `catch_exceptions'

**Comment by indykish** [comment]
Bind service in all the areas.
