### ISSUE TITLE
Apps launch issue

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/nilavu#577]
launch the app.but the ok box is not displayed 
![screenshot from 2015-10-15 16 01 46](https://cloud.githubusercontent.com/assets/13765880/10511435/b5ea5946-7356-11e5-81c8-232312bd8a58.png)

**Comment by indykish** [comment]
@ranjithamca  Your fix may have closed the above issue.

@rajthilakmca Please verify and reply here if this is still valid.

**Comment by arunkumarsekar06** [comment]
I've checked this issue on my localhost, but it's working correctly. so @ranjithamca please verify this issue once again.

**Comment by ranjithamca** [comment]
now it working correctly.The box displayed
