### ISSUE TITLE
VM doesn't create in Opennebula 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#598]
Status stays on creating sends request to megamd but doesn't create VM.

**Comment by indykish** [comment]
I checked the status flow. It moves from

| state | megamd | gulpd |
| --- | --- | --- |
| deploying | - |  |
| creating | 1 |  |
| bootstrapping |  | 2 |
| stateup | 1 |  |
| running |  | 2 |

`1` indicates status updated by `megamd` upon successful run. If there is a error then the status will appear as `error`
`2` indicates status updated by `gulpd` upon successful run. If there is an error then the status will appear as `error`
