### ISSUE TITLE
gitlab icon and Radio button on flymodal

### ISSUE THREAD

**Issue by morpheyesh** [megamsys/nilavu#605]
1. Gitlab icon is missing in BYOC which was previous present in disabled mode
2. radio button for choosing 'BYOC' and 'Starter pack' has changed.

**Comment by indykish** [comment]
Please make use of this opportunity to test gitlab as well.

**Comment by morpheyesh** [comment]
@indykish  Issue has been fixed!! Yet to get a pull request from @balajisek
