### ISSUE TITLE
total bucket object size is lower than user usage size 

### ISSUE THREAD

**Issue by rajthilakmca** [megamsys/nilavu#634]
Bucket details -  {:total_buckets=>1, :buckets=>[{:name=>"rrr_p", **:size=>"305 Bytes"**, :count=>2}], :total_size=>"305 Bytes"}

user usage - {"total_objects"=>"2", **"total_bytes"=>"8192"**, "last_update"=>"2015-11-05 09:47:44.135717Z"}

**Comment by indykish** [comment]
@rajthilakmca @thomasalrin  What is the fix for this problem ?

**Comment by thomasalrin** [comment]
Problem is in ceph. They show like that only. 
Before we started getting usage from ceph, @rajthilakmca had a solution by adding individual file's sizes.
