### ISSUE TITLE
I got the following error When i used wrong user password for Backup(Storage) 

### ISSUE THREAD

**Issue by arunkumarsekar06** [megamsys/nilavu#640]
RUN_NOW Megam::Organizations.list 
Inappropriate ioctl for device - tcgetattr
backup_user.rb:30:in `create'
nilavu_controller.rb:70:in`load_ceph'
nilavu_controller.rb:62:in `load_environments'
nilavu_controller.rb:20:in`block in class:NilavuController'
application_controller.rb:73:in `catch_exceptions'

```
   ,--.!,
__/   -*-
,####.  '|`
######
`####'                !We flunked!
```

  Rendered layouts/_notifications.html.erb (0.1ms)
  Rendered layouts/_header.html.erb (5.4ms)
  Rendered layouts/_footer.html.erb (0.4ms)
  Rendered errors/internal_server_error.html.erb within layouts/application (7.0ms)
  Rendered /var/lib/gems/2.0.0/gems/toastr_rails-2.1.1/app/views/toastr_rails/_flash.html.erb (0.2ms)
Completed 500 Internal Server Error in 2551ms (Views: 13.9ms)

**Comment by indykish** [comment]
@arunkumarsekar06 this is an issue in https://github.com/megamsys/radosgw-s3 gem.

**Comment by arunkumarsekar06** [comment]
@indykish okay, I'll close it from nilavu issue.

**Comment by indykish** [comment]
Here is the radosgw issue https://github.com/megamsys/radosgw-s3/issues/16
