### ISSUE TITLE
Secure web socket connection to megamd (wss://)

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#648]

**Comment by indykish** [comment]
When we move megamd to https, then we need to change nilavu to connect for logs using `wss`

**Comment by indykish** [comment]
https://madai.megam.io frontends megamd, and this  works. Nilavu is rigged with `wss://`. @arunkumarsekar06  @thomasalrin  For packaging , we add `wss://` to the `log` property in **nilavu.yml**
