### ISSUE TITLE
ws connection is not closing, on any links click

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/nilavu#654]

**Comment by indykish** [comment]
As per @rajthilakmca  cleanup, Socket connection closes, but cAdvisor ajax doesn't close.

**Comment by morpheyesh** [comment]
@all socket connection close was working just fine already..?!?

**Comment by indykish** [comment]
@morpheyesh  The cadvisor ajax connect isn't working.

**Comment by thomasalrin** [comment]
@morpheyesh It is not stable. We need to test again. Please show us the working result.
