### ISSUE TITLE
Show growl for errors when rabbitmq, riak are down. 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#659]
752490496","name":"flummox.megambox.com","cattype":"Microservices","action":null,"category":"control","command":null,"created_at":null}
App 3144 stdout: [2015-11-18T15:23:26+05:30] DEBUG: HTTP Request Data:
App 3144 stdout: [2015-11-18T15:23:26+05:30] DEBUG: > HTTP http://192.168.1.249
App 3144 stdout: [2015-11-18T15:23:26+05:30] DEBUG: > path: /v2/requests/content
App 3144 stdout: [2015-11-18T15:23:26+05:30] DEBUG: > body: {"json_claz":"Megam::Request","id":"ASM1278701284752490496","cat_id":"ASM1278701284752490496","name":"flummox.megambox.com","cattype":"Microservices","action":null,"category":"control","command":null,"created_at":null}
App 3144 stdout: [2015-11-18T15:23:26+05:30] DEBUG: > headers: {"Accept"=>"application/json", "Accept-Encoding"=>"gzip", "User-Agent"=>"megam-api/0.83", "X-Ruby-Version"=>"2.2.3", "X-Ruby-Platform"=>"x86_64-linux", "X-Megam-HMAC"=>"vijay@megam.io:524bf0c97d35dc7009aa1e3afd9e48fbc492f905", "X-Megam-DATE"=>"2015-11-18 15:23"}
App 3144 stdout: [2015-11-18T15:23:26+05:30] DEBUG: > host: 192.168.1.249
App 3144 stdout: [2015-11-18T15:23:26+05:30] DEBUG: > nonblock: false
App 3144 stdout: [2015-11-18T15:23:26+05:30] DEBUG: > scheme: http
App 3144 stdout: [2015-11-18T15:23:26+05:30] DEBUG: End HTTP Request Data.
App 3144 stdout: [2015-11-18T15:23:26+05:30] DEBUG: {
App 3144 stdout:   "code":500,
App 3144 stdout:   "msg_type":"error",
App 3144 stdout:   "msg":"Ooops ! I know its crazy. We flunked.\nContact support@megam.io with this text.\n            ",
App 3144 stdout:   "more":"Pardon us. This is how it happened.\nStack trace\njava.lang.Error: publish channel for [megam_flummox.megambox.com_exchange,megam_flummox.megambox.com_queue] not created\n\tat org.megam.common.amqp.RabbitMQClient$$anonfun$mkPublishChannel$1.apply(RabbitMQClient.scala:139)\n\tat org.megam.common.amqp.RabbitMQClient$$anonfun$mkPublishChannel$1.apply(RabbitMQClient.scala:139)\n\tat scalaz.Validation.getOrElse(Validation.scala:199)\n\tat org.megam.common.amqp.RabbitMQClient.mkPublishChannel(RabbitMQClient.scala:139)\n\tat org.megam.common.amqp.RabbitMQClient$$anonfun$executePublish$1.apply(RabbitMQClient.scala:154)\n\tat org.megam.common.amqp.RabbitMQClient$$anonfun$executePublish$1.apply(RabbitMQClient.scala:152)\n\tat scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)\n\tat scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\n\n            ",
App 3144 stdout:   "json_claz":"Megam::Error",
App 3144 stdout:   "links":"Forum   :http://docs.megam.io/discuss\nDocs    :http://docs.megam.io\nSupport :http://support.megam.io"
App 3144 stdout: }
App 3144 stdout: [2015-11-18T15:23:26+05:30] DEBUG: RESPONSE ERR: Ruby Object
App 3144 stdout: [2015-11-18T15:23:26+05:30] DEBUG: json_claz      =Megam::Error
App 3144 stdout: some_msg       ={:code=>500, :msg_type=>"error", :msg=>"Ooops ! I know its crazy. We flunked.\nContact support@megam.io with this text.\n            ", :links=>"Forum   :http://docs.megam.io/discuss\nDocs    :http://docs.megam.io\nSupport :http://support.megam.io"}
Gateway error. !
Expected(201) <=> Actual(500 InternalServerError)

api_dispatch.rb:51:in `rescue in api_request'
api_dispatch.rb:44:in`api_request'
requests.rb:27:in `reqs'
catalogs_controller.rb:43:in`create'
application_controller.rb:73:in `catch_exceptions'

```
   ,--.!,
__/   -*-
,####.  '|`
######
`####'                !We flunked!
```

**Comment by indykish** [comment]
@rajthilakmca @thomasalrin  @morpheyesh  The fix i had for healthcheck didn't work. It causes other issues for happy cases (like signed in session) and casues looping.

 Should we fix it using a react component and do it like trello ?
