### ISSUE TITLE
When you click service overview it flunks

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#685]
> ASB'S: END
> undefined method `components' for nil:NilClass
> oneservices_controller.rb:26:in`index'
> application_controller.rb:73:in `catch_exceptions'

```
   ,--.!,
__/   -*-
,####.  '|`
######
`####'                !We flunked!
```

  Rendered layouts/_notifications.html.erb (0.0ms)
  Rendered layouts/_header.html.erb (5.9ms)
  Rendered layouts/_footer.html.erb (0.2ms)
  Rendered errors/internal_server_error.html.erb (7.5ms)
Completed 500 Internal Server Error in 216ms (Views: 13.2ms)

**Comment by indykish** [comment]
@morpheyesh  Please fix this.
