### ISSUE TITLE
cadvisor port(9999) needs to be get from nilavu.yml

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/nilavu#700]
Now, it is static in code

**Comment by arunkumarsekar06** [comment]
Actually now I set the port number (9999) manually. I'll fix it soon.

**Comment by arunkumarsekar06** [comment]
I'll fix it later

On Thu, Dec 10, 2015 at 11:52 AM, Arun kumar Sekar <arunkumar.sekar@megam.io

**Comment by indykish** [comment]
@thomasalrin  @morpheyesh  fixed ?

**Comment by thomasalrin** [comment]
@indykish not yet. @morpheyesh Please fix this.

**Comment by indykish** [comment]
@thomasalrin  Let close it, as it does no harm for now.
