### ISSUE TITLE
megambox.com shall be editable 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#713]

**Comment by indykish** [comment]
@vijaykanthm28  @thomasalrin  Are we ready for this ?

**Comment by thomasalrin** [comment]
@indykish Need to test it. Shall we try by adding any of our domain other than megambox.com in route53?

**Comment by indykish** [comment]
@thomasalrin  Are you saying there is a fix, we need to test it ?

**Comment by thomasalrin** [comment]
@indykish yes. As @rajthilakmca suggested, we can move the domain name to nilavu.yml.

**Comment by indykish** [comment]
@thomasalrin  Then we don't have fix, please fix it.
