### ISSUE TITLE
Minimum cut off to limit a user to have a single vm

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/nilavu#736]

**Comment by indykish** [comment]
@thomasalrin  Will have to be tested.

**Comment by thomasalrin** [comment]
@indykish ok, you said that, it will be fixed, when billing work is finished.

**Comment by indykish** [comment]
@thomasalrin  Yes, :) There is code for billing in `vertice` and can be tested.

**Comment by indykish** [comment]
@rajthilakmca  This gets closed in our billing evented mode.

**Comment by indykish** [comment]
This will be closed in the clean biller fix, i will be pushing today
