### ISSUE TITLE
when click marketplaces icons 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#737]
Started GET "/marketplaces/Play" for 162.158.54.92 at 2016-01-18 13:29:52 +0530
Processing by MarketplacesController#show as JS
  Parameters: {"id"=>"Play"}
FASCADE Megam::Balancesshow 
Your credentials are missing. Did you signup with us ?
api_dispatch.rb:106:in `satisfied_args?'
api_dispatch.rb:50:in`api_request'
balances.rb:25:in `show'
marketplaces_controller.rb:119:in`visit_paisa'
application_controller.rb:73:in `catch_exceptions'

```
   ,--.!,
__/   -*-
,####.  '|`
######
`####'                !We flunked!
```

**Comment by indykish** [comment]
@vijaykanthm28  Is this a sev1 bug ? If so please ask for help and close it.

**Comment by indykish** [comment]
@vijaykanthm28  fixed ?
