### ISSUE TITLE
Inside /cockpit - Mixed Content - Cannot load data over HTTP.

### ISSUE THREAD

**Issue by jaeko44** [megamsys/nilavu#743]
Mixed Content: The page at 'https://console.megam.io/cockpits' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://shatterproof.megambox.com:9999/api/v1.3/containers'. This request has been blocked; the content must be served over HTTPS.support.cors.options.crossDomain.send @ application-ccdd4522a871e2c68845363cc9696e26c2872a7774412bc0d3279d9ef761b39e.js:2
application-ccdd4522a871e2c68845363cc9696e26c2872a7774412bc0d3279d9ef761b39e.js:2 Mixed Content: The page at 'https://console.megam.io/cockpits' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://shatterproof.megambox.com:9999/api/v1.3/machine'. This request has been blocked; the content must be served over HTTPS.support.cors.options.crossDomain.send @ application-ccdd4522a871e2c68845363cc9696e26c2872a7774412bc0d3279d9ef761b39e.js:2

**Comment by thomasalrin** [comment]
@jaeko44 this is a cross domain problem. To solve this issue, click on the shield in your browser url field, and load unsafe scripts.

**Comment by jaeko44** [comment]
Alright I just fixed that,

Now it displays: 
GET http://shatterproof.megambox.com:9999/api/v1.3/containers net::ERR_NAME_NOT_RESOLVED
XHR failed loading: GET "http://shatterproof.megambox.com:9999/api/v1.3/containers".
GET http://shatterproof.megambox.com:9999/api/v1.3/machine net::ERR_NAME_NOT_RESOLVED
XHR failed loading: GET "http://shatterproof.megambox.com:9999/api/v1.3/machine".

**Comment by indykish** [comment]
@jaeko44  We shutdown the servers in the nite as its staging. You can try it again 12 hrs from now.

**Comment by indykish** [comment]
@jaeko44  Do you have a need to setup such environment in your firm ?

**Comment by jaeko44** [comment]
Yes I have the hardware required can you help me setup an environment?

**Comment by indykish** [comment]
@jaeko44  Yes sure buddy. 
- Here is our email `nkishore@megam.io`, 
- We also have a `slack channel` [https://megamioteam.slack.com/messages/support/](https://megamioteam.slack.com/messages/support/)
- Support issues email `support@megam.io`

Can you send us an email please, just so we can collaborate better. ?

Hope you read our docs [http://docs.megam.io](https://megamioteam.slack.com/messages/support/)

Our product [vertice](http://docs.megam.io/docs/megam_oja) has packages and easy setup tool supported in _Ubuntu 14.04_, hope you are ok with that ? 

We have customer interest requesting support [vertice](http://docs.megam.io/docs/megam_oja)  on CentOS 7.1, Debian Wheezy, and Docker Containers and we will tweak [packager project](http://github.com/megamsys/packager.git) shortly.

**Comment by indykish** [comment]
@jaeko44  May i close this issue then ? Or do you want to try tomorrow around 11AM India time ? Its heavily under testing. 

Let me know.
