### ISSUE TITLE
signup page flag gets delay to load 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#746]

**Comment by rajthilakmca** [comment]
@vijaykanthm28 @thomasalrin @indykish @morpheyesh @ranjithamca 
flags gets fast to load from local testing, may be we should test on production side

**Comment by indykish** [comment]
Yeah @rajthilakmca can we check flag image sizes ?

**Comment by indykish** [comment]
@rajthilakmca  Debug in staging. I get a feeling that the flags are behind CDN cloudflare. (might be a low priority issue)

**Comment by indykish** [comment]
@vijaykanthm28  check this out in todays build. clear your cache in browser.
