### ISSUE TITLE
dashboard grid and list view appear on same page

### ISSUE THREAD

**Issue by rajthilakmca** [megamsys/nilavu#749]
when click sidebar dashboard link the grid and list view appears on same page
![dashboard_bug](https://cloud.githubusercontent.com/assets/3692486/12476608/894257e4-c050-11e5-8f2f-da5a3682cc11.png)

**Comment by indykish** [comment]
@rajthilakmca  Nice issue, wanted to capture this, glad you fixed it.

**Comment by rajthilakmca** [comment]
fixed
