### ISSUE TITLE
riak down gets flunked 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#753]
Completed 200 OK in 79ms (Views: 32.5ms)
Started GET "/cockpits" for 162.158.54.92 at 2016-01-21 20:11:25 +0530
Processing by CockpitsController#index as HTML
Connection refused - connect(2)
gsriak.rb:41:in `fetch'
configuration.rb:25:in`load'
sessions_helper.rb:26:in `current_user'
sessions_helper.rb:20:in`signed_in?'
nilavu_controller.rb:28:in `require_signin'
application_controller.rb:73:in`catch_exceptions'

```
   ,--.!,
__/   -*-
,####.  '|`
######
`####'                !We flunked!
```

  Rendered layouts/_notifications.html.erb (0.1ms)
  Rendered layouts/_header.html.erb (4.8ms)
  Rendered layouts/_footer.html.erb (0.4ms)
  Rendered errors/internal_server_error.html.erb within layouts/application (6.2ms)
  Rendered /var/lib/gems/2.0.0/gems/toastr_rails-2.1.1/app/views/toastr_rails/_flash.html.erb (0.2ms)
Completed 500 Internal Server Error in 21ms (Views: 12.8ms)
Started GET "/assets/ElegantIcons.woff" for 162.158.54.14 at 2016-01-21 20:11:26 +0530
Started GET "/cockpits" for 162.158.54.92 at 2016-01-21 20:22:10 +0530
Processing by CockpitsController#index as HTML
Expected success from Riak but received 0. {insufficient_vnodes,0,need,2}
gsriak.rb:39:in `fetch'
configuration.rb:25:in`load'
sessions_helper.rb:26:in `current_user'
sessions_helper.rb:20:in`signed_in?'
nilavu_controller.rb:28:in `require_signin'
application_controller.rb:73:in`catch_exceptions'

```
   ,--.!,
__/   -*-
,####.  '|`
######
`####'                !We flunked!
```

  Rendered layouts/_notifications.html.erb (0.1ms)
  Rendered layouts/_header.html.erb (4.8ms)

**Comment by indykish** [comment]
This may not be valid after we all the calls to riak via api (gateway). Hence `wontfix`.
