### ISSUE TITLE
Storage, doesn't work

### ISSUE THREAD

**Issue by indykish** [megamsys/nilavu#757]
When i click on storage nothing is shown, a spinner just spins.

**Comment by indykish** [comment]
@thomasalrin  fixed ?

**Comment by thomasalrin** [comment]
@indykish need to fix. The radosgw service was not running, when we tested. We should show, connection error.

**Comment by thomasalrin** [comment]
related to https://github.com/megamsys/nilavu/issues/759. So let me close this issue.
