### ISSUE TITLE
SSH Created successfully title and message needs to be meaningful

### ISSUE THREAD

**Issue by indykish** [megamsys/nilavu#758]
![screenshot from 2016-01-22 17-06-40](https://cloud.githubusercontent.com/assets/1402479/12509772/d61695aa-c12a-11e5-878e-1e3fa32a4382.png)

**Comment by thomasalrin** [comment]
@indykish we should use toastr instead of modal.

**Comment by indykish** [comment]
@thomasalrin  yes. sure.

**Comment by indykish** [comment]
@thomasalrin  fixed ?

**Comment by thomasalrin** [comment]
@indykish Fixed for ssh key creation, but upload.

**Comment by indykish** [comment]
Opened #772 for upload. closing this issue.
