### ISSUE TITLE
When i click on the top left dropdown button "New/Storage" nothing happens.

### ISSUE THREAD

**Issue by indykish** [megamsys/nilavu#759]

**Comment by thomasalrin** [comment]
The radosgw service was not running, when we tested. We should show, connection error.

**Comment by indykish** [comment]
This can be done easily, by adding "CephHealthCheck"

**Comment by indykish** [comment]
So the fix is to add an AuthProvider for ceph, which provides StorageUser. 
Two conditions - Happy path (Storage working, hence we onboard the user during signup)
Onboard turned on after some time, hence user isn't onboard in ceph. In this case we provide a link or onboard when the user clicks `storage`.
