### ISSUE TITLE
Forgot password doesn't work. It just sits there.

### ISSUE THREAD

**Issue by indykish** [megamsys/nilavu#762]

**Comment by indykish** [comment]
No refresh yet, all in dom.
1. I clicked on signup, click `Verify for otp` and i get the "window -loc error".
2. I again put my mobile no, this time there is flag as well. i receive the `window-loc-error`
3. I see the flag now, i put my mobile and click verify, receive the error "Sending OTP failed"
4. I clicked **Login**
5. Clicked **Forgot PW**, the modal just remains.

**Comment by indykish** [comment]
unable to recreate by raj.

@rajthilakmca  What do you intend to do with this bug ?

**Comment by indykish** [comment]
@thomasalrin  By trapping errors in OTP this can be avoided.  Test the OTP code and  see if this is fixed

**Comment by thomasalrin** [comment]
@indykish ok
