### ISSUE TITLE
Region: India by default

### ISSUE THREAD

**Issue by jaeko44** [megamsys/nilavu#781]
Allow host to have a region variable with each location grabbing the correct flag.

**Comment by indykish** [comment]
@jaeko44  Yes.
@vijaykanthm28  Fix it in the next build.  @thomasalrin  fya.

**Comment by indykish** [comment]
@jaeko44  Check this fix in today's build. @thomasalrin  Have some one set it up for @jaeko44

**Comment by thomasalrin** [comment]
@indykish , @ranjithamca will do the vertice set up for  @jaeko44, after we complete our basic testing on vertice.
