### ISSUE TITLE
Machines that fail to deploy are not properly logged instead the user sees 'Launched' 

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/nilavu#813]
cases : 
1. trying to deploy CentOS when there is no CentOS template(image)
2. When there is no ip
3. When there is no resources(like ram, cpu, datastore etc)

^ In a scenario where the above causes a failed deployment, the user must be notified what is the issue & administrator must be notified with issue as a log.
    Via EMAIL tagged as 'Failed Deployment'

**Comment by indykish** [comment]
we now have a predeploy page.
