### ISSUE TITLE
Cannot destory VMs

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#821]
FASCADE Megam::Requestcreate 
Nilavu::InvalidParameters
api_dispatch.rb:44:in `api_request'
requests.rb:27:in`reqs'
catalogs_controller.rb:55:in `destroy'
global_exceptions.rb:4:in`catch_exceptions'

```
   ,--.!,
__/   -*-
,####.  '|`
######
`####'                !We flunked!
```

Completed 200 OK in 2ms

**Comment by indykish** [comment]
@ranjithamca  fixed, test it out.
