### ISSUE TITLE
create and import ssh key flunked

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#823]
Nilavu::InvalidParameters
api_dispatch.rb:44:in `api_request'
sshkeys.rb:66:in`create'
sshkeys.rb:39:in `create_or_import'
ssh_keys_controller.rb:29:in`create'
global_exceptions.rb:4:in `catch_exceptions'

```
   ,--.!,
__/   -*-
,####.  '|`
######
`####'                !We flunked!
```

Completed 200 OK in 81ms

**Comment by thomasalrin** [comment]
Create ok, only import get flunked

**Comment by vijaykanthm28** [comment]
Create and Import keys fixed @thomasalrin
