### ISSUE TITLE
 click owncloud overviewpage doesn't open

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/nilavu#831]
FASCADE Megam::Componentsshow
START Megam::Components.show
type: SERVICE
controller: deploys
action: show
id: COM7974253927388805416
email: ranjithar@megam.io
api_key: fa58d4952ec03053ac22fed8fca9a3e5a83f4d8d
org_id: ORG5994251550417621083
host: 192.168.1.105
RUN_NOW Megam::Components.show
-- ASC: START
{"COLLABORATION"=>#<Megam::Assembly:0x007fb4da01e0c8 @id="ASM6393851015529652018", @asms_id=nil, @name="antiaircraft", @components=[#<Megam::ComponentsCollection:0x007fb4da02ca10 @components=[#<Megam::Components:0x007fb4da02d280 @id="COM7974253927388805416", @name="ritz", @tosca_type="tosca.collaboration.zarafa", @inputs=[{"key"=>"domain", "value"=>"megambox.com"}, {"key"=>"sshkey", "value"=>"rr"}, {"key"=>"provider", "value"=>"one"}, {"key"=>"cpu", "value"=>"1 Core"}, {"key"=>"ram", "value"=>"1 GB"}, {"key"=>"hdd", "value"=>"24 GB SSD"}, {"key"=>"version", "value"=>"7.2"}, {"key"=>"status", "value"=>"launched"}, {"key"=>"lastsuccessstatusupdate", "value"=>"16 Mar 16 17:54 IST"}], @outputs=[], @envs=[{"key"=>"port", "value"=>"9000"}], @artifacts={:artifact_type=>"", :content=>""}, @artifact_type=nil, @content=nil, @artifact_requirements=[], @related_components=[], @operations=[], @status="launched", @repo={:rtype=>"", :source=>"", :oneclick=>"", :url=>""}, @rtype=nil, @source=nil, @oneclick=nil, @url=nil, @created_at="2016-03-16 12:24:26 +0000", @email=nil, @api_key=nil, @host=nil, @password=nil, @org_id=nil>], @components_by_name={"ritz"=>0}, @insert_after_idx=nil>], @tosca_type="tosca.collaboration.zarafa", @policies=[], @inputs=[{"key"=>"domain", "value"=>"megambox.com"}, {"key"=>"sshkey", "value"=>"rr"}, {"key"=>"provider", "value"=>"one"}, {"key"=>"cpu", "value"=>"1 Core"}, {"key"=>"ram", "value"=>"1 GB"}, {"key"=>"hdd", "value"=>"24 GB SSD"}, {"key"=>"version", "value"=>"7.2"}, {"key"=>"lastsuccessstatusupdate", "value"=>"16 Mar 16 17:54 IST"}, {"key"=>"status", "value"=>"launched"}], @outputs=[], @status="launched", @created_at="2016-03-16 12:24:26 +0000", @email=nil, @api_key=nil, @host=nil, @password=nil, @org_id=nil>}
ASC: END
Nilavu::NotFound
deployed_runner.rb:15:in `perform_run'
deploys_controller.rb:7:in`show'
global_exceptions.rb:4:in `catch_exceptions'       ,--.!,
   __/   -*-
    ,####.  '|`
    ######
    `####'                !We flunked!Completed 200 OK in 13ms

**Comment by indykish** [comment]
@ranjithamca  fixed, check it out.
