### ISSUE TITLE
lauuch services the overview page os icon is changed

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/nilavu#841]
![os](https://cloud.githubusercontent.com/assets/13765880/13851533/92fb2b5c-ec84-11e5-8e80-ba8c1ea79f79.png)

**Comment by thomasalrin** [comment]
@ranjithamca Which marketplace item you launched?

**Comment by ranjithamca** [comment]
i launch apache marketplace item

RANJITHA R
Platform Developer, Megam Systems
m: 9865693466 a: Megam systems, Plot no. 53, D.no 2/1075, Second cross, Ist
floor, Radha nagar, Perumbakkam, Chennai, Tamil Nadu 600100, India (map)
s: http://megam.io/ e: ranjithar@megam.io
http://twitter.com/Ranjitha

**Comment by indykish** [comment]
Icon isn't the issue here as i can see the correct icon, the term `OS` is misleading here. That needs to be changed.

**Comment by indykish** [comment]
WAD - working as designed.
