### ISSUE TITLE
Dashboard - Vm settings dropdown not closing on vm delete

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/nilavu#844]
![vm-delete](https://cloud.githubusercontent.com/assets/1989260/13857861/d7a6b6d2-eca1-11e5-9c04-38801541809d.png)

**Comment by indykish** [comment]
Won't fix. 

May in 2.0 we'll add the "control group"

https://gitlab.com/megamsys/nilavu.git (MegamVertice/VirtEngine - Complete Edition)
