### ISSUE TITLE
storage object needs an action for "make it as public or private"

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/nilavu#851]
*\* Private object url : "**http://GW_IP/Test/Megam-Menu-Concept.png?AWSAccessKeyId=3HOD6BH8IU27684QJAVQ&Expires=1458551073&Signature=%2FBsOqhJ9vXmmnpi0dOLmvv2rU%2Bk%3D"

Public url should be "http://GW_IP/Test/Megam-Menu-Concept.png"

**Comment by indykish** [comment]
Fixed in https://gitlab.com/megamsys/nilavu.git
