### ISSUE TITLE
Launch container the page will be blank

### ISSUE THREAD

**Issue by ranjithamca** [megamsys/nilavu#862]
param is missing or the value is empty: sshoption
launchers_controller.rb:40:in `perform_launch'
global_exceptions.rb:4:in`catch_exceptions'

```
   ,--.!,
__/   -*-
,####.  '|`
######
`####'                !We flunked!
```

Completed 200 OK in 2ms

**Comment by indykish** [comment]
Can you comment the line `params.require(:sshoption)` and try it out. ?

``` ruby
def perform_launch
    params.require(:version)
    params.require(:assemblyname)
    params.require(:componentname)
   // params.require(:sshoption)
```

**Comment by ranjithamca** [comment]
undefined method `include?' for nil:NilClass
sshkeys_creator.rb:29:in`has_old_keypair?'
sshkeys_creator.rb:33:in `keypair_name'
sshkeys_creator.rb:17:in`save'
vertice_launcher.rb:17:in `set_sshkey'
vertice_launcher.rb:22:in`launch'
launchers_controller.rb:44:in `perform_launch'
global_exceptions.rb:4:in`catch_exceptions'

```
   ,--.!,
__/   -*-
,####.  '|`
######
`####'                !We flunked!
```

Completed 200 OK in 11ms

**Comment by indykish** [comment]
Fix in `sshkeys_creator` 

``` ruby
def save
   return  unless @option

    @params[:ssh_keypair_name]  =  keypair_name

    return autoset_sshkey if has_old_keypair?

    if ssh = Api::Sshkeys.new.create_or_import(@params)
      @name = ssh[:name]
    end
  end
```

**Comment by ranjithamca** [comment]
RUN_NOW Megam::SshKey.list 
Nilavu::NotFound
vertice_launcher.rb:22:in `launch'
launchers_controller.rb:44:in`perform_launch'
global_exceptions.rb:4:in `catch_exceptions'

```
   ,--.!,
__/   -*-
,####.  '|`
######
`####'                !We flunked!
```

Completed 200 OK in 15ms

**Comment by indykish** [comment]
Temporary hack.

`return  :sshoption unless @option`

**Comment by ranjithamca** [comment]
RUN_NOW Megam::SshKey.list 
Nilavu::InvalidParameters
vertice_launcher.rb:37:in `block in ensure_settings_are_ok'
vertice_launcher.rb:36:in`each'
vertice_launcher.rb:36:in `ensure_settings_are_ok'
vertice_launcher.rb:26:in`launch'
launchers_controller.rb:44:in `perform_launch'
global_exceptions.rb:4:in`catch_exceptions'

```
   ,--.!,
__/   -*-
,####.  '|`
######
`####'                !We flunked!
```

Completed 200 OK in 13ms

**Comment by indykish** [comment]
`vertice_launcher.rb` line 37
Remove the setting  

`````` ruby
 [:cpu, :ram, :hdd, :assemblyname, :componentname, :provider, :version, :cattype].each do |setting|```
``````

**Comment by indykish** [comment]
@ranjithamca  Revert the fix and let the other testing continue, do a local clone of 1.0 nilavu and check it out. 

Basically you need to skip `sshkeyoption` for microservice.
