### ISSUE TITLE
 nilavu conf we have to support also for https

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/nilavu#866]
there is only http_api = 192.168.1.1

**Comment by indykish** [comment]
I see that in the megam_api ruby we use a flag `:scheme` to detect `https` or not.

We'll need this if we want to run under `https`

**Comment by indykish** [comment]
I think this is fixed.
Fixed in https://gitlab.com/megamsys/nilavu.git (MegamVertice/VirtEngine - Complete Edition)
