### ISSUE TITLE
Logout action is not working when the email has symbol(ss.j@gmail.com)

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/nilavu#932]

**Comment by indykish** [comment]
Nilavu ember when it calls rails has a filter regex for security. The change is in config/routes.rb file.

@vinomca-megam  Simple to knockoff, just change the `conf/routes.rb` REGEX

**Comment by indykish** [comment]
session also not closed.It causes the routing error

**Comment by vinomca-megam** [comment]
I removed the constraints when sessions#destroy  is called in config/routes.rb.but it doesn't work.The same problem happened.

**Comment by indykish** [comment]
Ok, i guess we can remove the email@ id itself, as its not needed to be sent from ember.

**Comment by vinomca-megam** [comment]
I removed the email id from ajax request.Now it works
