### ISSUE TITLE
while choosing the c1.large(3GB, 3core) in the first time, is can't selected, either choose c1.micro or c1.medium then only c1.large is selected

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/nilavu#948]

**Comment by indykish** [comment]
Yeah this is an universal problem (happens in all of the selections in the UI in the new launch dialog.)

That means we have left something fundamental.

**Comment by indykish** [comment]
@vinomca-megam  Please refactor your `https://github.com/megamsys/onboardcloud/blob/master/portal/app/assets/javascripts/nilavu/components/radio-button.js.es6` with the fix here. This should fix your radio selection problem.
