### ISSUE TITLE
In nilavu UI - show the latest 10 vm's only. others are shows when we click the more options.

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/nilavu#957]

**Comment by indykish** [comment]
Nice to have problem. We will have a stop gap  fix next week to show the last 2 successfu/failure ones on the left nav bar. 

Will wait for @jaeko44's nav bar fix to be put in.

**Comment by indykish** [comment]
Will have a functional fix ready in the current navbar version itself.
