### ISSUE TITLE
after clicking the new button, then doesn't open the app, services. once refresh the page then only it will work.

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/nilavu#963]

**Comment by indykish** [comment]
Yeah, a darn nagging bug..

**Comment by indykish** [comment]
not yet fixed.

**Comment by indykish** [comment]
@rajthilakmca  Can you try this with `new-topic` route ? With the fix #975 `modal was improved`.  We may get the `hit (or) stale` behaviour as asked in #1010
