### ISSUE TITLE
Aesthetic: Logs appears bold.

### ISSUE THREAD

**Issue by indykish** [megamsys/nilavu#968]
We need to polish the logs screen.

![screenshot from 2016-07-11 19-12-42](https://cloud.githubusercontent.com/assets/1402479/16732567/788e05ce-479b-11e6-94a0-742680b20f48.png)

@jaeko44  I am sending off aesthetic stuff to you.

**Comment by jaeko44** [comment]
![logs](https://cloud.githubusercontent.com/assets/9289791/17366984/601706a6-59d1-11e6-821c-683f79696156.png)
Is this any better? (fixed alignment and some color) @indykish

**Comment by rajthilakmca** [comment]
@jaeko44 it looks better, please give pull request this code, then we check it

**Comment by indykish** [comment]
@jaeko44  Yes, looks better.
