### ISSUE TITLE
Aesthetic: Custom application

### ISSUE THREAD

**Issue by indykish** [megamsys/nilavu#969]
1. When the select box is triggered initially, it appears good.

![screenshot from 2016-07-11 19-17-25](https://cloud.githubusercontent.com/assets/1402479/16732751/4004b3e6-479c-11e6-9165-97565cbf2d9c.png)
1. Upon selecting "Nodejs", it shrinks.
   ![screenshot from 2016-07-11 19-17-56](https://cloud.githubusercontent.com/assets/1402479/16732799/7e197932-479c-11e6-9534-d1abd0cc9821.png)
2. If i click and open the select box again it shows in the smaller width.
3. The customapp dialog needs to be skinned well. It doesn't appear well put together.

@jaeko44  Send it over to you.

**Comment by jaeko44** [comment]
![app-launch-aligned](https://cloud.githubusercontent.com/assets/9289791/18233639/f41f70b4-732f-11e6-8118-b5f8b1bcd72c.png)

@indykish the app launch is aligned properly now.

Regarding the shrinking issue, i don't think it's much of an issue. If we really want to show a logo of the technology, we can put it to the left of 'NodeJS Version 4.4 LTS : Launch an ....' text.

**Comment by indykish** [comment]
@jaeko44  :+1:  Looks good. Sure.

Are the label colors (blue, green, yellow) look ok ?
