### ISSUE TITLE
Aesthetic: Disto images in sprite doesn't get loaded correctly

### ISSUE THREAD

**Issue by indykish** [megamsys/nilavu#970]
I used the distro images as we discussed from this file 
https://github.com/megamsys/nilavu/blob/1.5/public/images/launch/vmdistros.png

But it doesn't get loaded correctly.

![screenshot from 2016-07-11 19-25-22](https://cloud.githubusercontent.com/assets/1402479/16732991/3b89456a-479d-11e6-973f-eadf033304f1.png)

**Comment by jaeko44** [comment]
Done 
![ss 2016-07-28 at 11 34 28](https://cloud.githubusercontent.com/assets/9289791/17214351/dd5e7faa-551b-11e6-934a-52844a77fc0e.png)
