### ISSUE TITLE
Launching a bitnami - tosco type changes

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/nilavu#995]
it created in this format "tosca.collaboration.wordpress".. change into tosca.bitnami.wordpress

**Comment by indykish** [comment]
@rajesh-rajagopal  Is this done ?  or do you still have an issue ?

**Comment by rajesh-rajagopal** [comment]
should add the provider name in bitnami

**Comment by indykish** [comment]
@vijaykanthm28  Please fix `vertice` lets get another round of testing with the fixes.
